String[] description = {
   "A central theme of anti-LGBT organizing and ideology is the opposition to LGBT rights, often couched in rhetoric and harmful pseudoscience that demonizes LGBT people as threats to children, society and often public health.",
   "Anti-Muslim hate groups are a relatively new phenomenon in the United States, with many appearing in the aftermath of the World Trade Center terrorist attacks on Sept. 11, 2001. Beginning in 2010,  anti-Muslim legislation increased and opposition to the development of an Islamic Center in lower Manhattan made headlines.",
   "The black nationalist movement is a reaction to centuries of institutionalized white supremacy in America. Black nationalists believe the answer to white racism is to form separate institutions — or even a separate nation — for black people. Most forms of black nationalism are strongly anti-white and anti-Semitic. Some religious versions assert that black people are the biblical \"chosen people\" of God.",
   "Christian Identity is a unique anti-Semitic and racist theology that rose to a position of commanding influence on the racist right in the 1980s. \"Christian\" in name only, the movement's relationship with evangelicals and fundamentalists has generally been hostile due to the latter’s belief that the return of Jews to Israel is essential to the fulfillment of end-time prophecy.",
   "Anti-immigrant hate groups are the most extreme of the undreds of nativist and vigilante groups that have proliferated since the late 1990s, when anti-immigration xenophobia began to rise to levels not seen in the United States since the 1920s.",
   "Hate music groups are typically white power music labels that record, publish and distribute racist music in a variety of genres.",
   "Deniers of the Holocaust, the systematic murder of around 6 million Jews in World War II, either deny that such a genocide took place or minimize its extent. These groups (and individuals) often cloak themselves in the sober language of serious scholarship, call themselves \"historical revisionists\" instead of deniers, and accuse their critics of trying to squelch open-minded inquiries into historical truth.",
   "These groups espouse a variety of rather unique hateful doctrines and beliefs that are not easily categorized. Many of the groups are vendors that sell a miscellany of hate materials from several different sectors of the white supremacist movement.",
   "\"Radical traditionalist\" Catholics, who may make up the largest single group of serious antisemites in America, subscribe to an ideology that is rejected by the Vatican and some 70 million mainstream American Catholics.",
   "The Ku Klux Klan, with its long history of violence, is the most infamous — and oldest — of American hate groups. Although black Americans have typically been the Klan's primary target, it also has attacked Jews, immigrants, gays and lesbians and, until recently, Catholics.",
   "Male supremacy is a hateful ideology advocating for the subjugation of women.",
   "\"Neo-Confederacy\" refers to a reactionary, revisionist predilection for symbols of the Confederate States of America (CSA), typically paired with a strong belief in the validity of the failed doctrines of nullification and secession — in the specific context of the antebellum South — which rose to prominence in the late 20th and early 21st centuries.",
   "Neo-Nazi groups share a hatred for Jews and a love for Adolf Hitler and Nazi Germany. While they also hate other minorities, gays and lesbians and even sometimes Christians, they perceive \"the Jew\" as their cardinal enemy.",
   "Racist Skinheads form a particularly violent element of the white supremacist movement, and have often been referred to as the  \"shock troops\" of the hoped-for revolution. The classic Skinhead look is a shaved head, black Doc Martens boots, jeans with suspenders and an array of typically racist tattoos.",
   "White nationalist groups espouse white supremacist or white separatist ideologies, often focusing on the alleged inferiority of nonwhites. Groups listed in a variety of other categories - Ku Klux Klan, neo-Confederate, neo-Nazi, racist skinhead, and Christian Identity - could also be fairly described as white nationalist."
};
